name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiiiisx/pacman-contribution-graph@master
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: "main"
          commit_message: "Generate new pacman-contribution-graph."
